# Generated by Django 5.2.4 on 2025-07-27 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='can_create',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_delete',
            field=models.BooleanField(default=False),
        ),
    ]
